### ISSUE TITLE
Decompile/Program

### ISSUE THREAD

**Issue by Flipgirl** [reakain/Sprout-Valley-Save-Editor#1]
Hello, I hope you are having a wonderful day. I wanted to reach out and ask you how you were able to use the program. I downloaded what you recommended to decompile, but I am having issues because in my pc I can't find the save file. All I see is a .vdf file and I can't decompile that, it gives me an error. I hope I can figure this out because your program is what I have been looking for 3 days straight! Thank you so much. Blessings

Update: It seems I was able to decompile but now I don't know where the save file is or how to open it with the program.

**Comment by reakain** [comment]
I'm so sorry for the very delayed reply! Unless the encryption key is different per game copy (which I don't think it is), you should be able to simply download the compiled save editor from the [releases](https://github.com/reakain/Sprout-Valley-Save-Editor/releases/tag/v0.0.2), and use that to edit your saves. The program should already have the correct encryption key, but it's something you can change in case the encryption key changes for some reason.

Your save data should be located in %APPDATA%\Godot\app_userdata\Sprout Valley if you're on Windows. Or  $HOME/.godot/app_userdata/Sprout Valley on GNU/Linux

For Windows in particular %APPDATA% refers to the AppData/Roaming folder in your user directory. (Aka, if your username is Reakain and your local disk is C, %APPDATA% would be: C:\Users\Reakain\AppData\Roaming )

Hopefully that helps, and I'm not too late on the reply!
